### ISSUE TITLE
Some config parameters meaning

### ISSUE THREAD

**Issue by andreqwert** [Livox-SDK/livox_lane_detection#2]
Could you please explain more accurate what do you mean describing the following parameters:
`distance_resolution_train`
`width_resolution_train`
`train_background_intensity_shift`?

**Comment by Livox-SDK** [comment]
Hi, andreqwert,

"distance_resolution_train"/ "width_resolution_train":
In real world, 1 meters long object in x-axis or y-axis direction will be divided as 6 or 30 pixels

train_background_intensity_shift:
In our real life, since the reflation rate for some objects are quite low, the intensity defined as a float, after calculation, the intensity value for those detected points may reach to zero. Therefore, we shift those values by 0.1, so that, these low reflection rate objects could be different from non-object points
